"""add_indices_to_revisions

Revision ID: 6ecf4d9d0094
Revises: 144d001863ce
Create Date: 2026-06-28 19:44:04.545782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecf4d9d0094'
down_revision: Union[str, Sequence[str], None] = '144d001863ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_revisions_page_id'), 'revisions', ['page_id'], unique=False)
    op.create_index(op.f('ix_revisions_timestamp'), 'revisions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_timestamp'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_page_id'), table_name='revisions')
    # ### end Alembic commands ###
